site_name: BurningMyself
site_description: .net,java,php,python,docker,web
site_author: 朽木自雕
site_url: https://burningmyself.github.io/blog/

repo_name: 'burningmyself/blog'
repo_url: 'https://github.com/burningmyself/blog'

theme:
  name: material
nav: 
  - 介绍: index.md 
  - 技术博文: 
    - .NET: 
        - C# 6: net/c_sharp.md
        - .Ner Core Docker 部署: net/c_docker.md
        - 使用 Docker 容器化部署 ASP.NET Core + MySQL + Nginx: net/c_mysql_nginx.md
        - 让你的ASP.NET Core应用程序更安全: net/c_core_safety.md
        - ASP.NET Core开发者指南: net/c_core_study_route.md
    - Java: 
        - Java特性: java/feature.md 
        - Java类加载: java/load-class.md
        - Orm的优缺点: java/orm.md
        - BIO与NIO: java/bio-nio.md
        - RocketMq下载与安装: java/rocketmq/rmq-1.md
        - Spring常用注解: java/springAnnotation.md
    - Python: 
        - Python特性: python/feature.md 
        - Python字符拼接: python/str_joint.md
        - Python语法技巧: python/syntax_rule.md
        - 远程部署神器 Fabric: python/fabric.md
    - PHP: 
        - 框架: php/kj.md    
    - Web:
        - es6语法: web/es6.md
        - 阿里js样式规范: web/ali_js_style.md
        - node.js文档: web/node.js.md
        - React 开发者指南: web/react.md
        - Dart语法学习: dart/syntax.md
        - React 面试: web/react_interview.md
        - js 工具函数: web/js_tool_method.md
        - vue与react比较: web/vue-cp-react.md
    - SQL:
        - MySQL优化: sql/mysql_yh.md
        - MySQL优化: sql/mysql_yh17.md
        - MySQL日志: sql/mysql_log.md
        - MySQL索引: sql/mysql_index.md
        - MySQL PXC集群: sql/mysql_pxc.md
        - MySQL 数据库应用: sql/mysql_use.md
        - Sql Server 主从备份: sql/sql_server_master.md
        - 数据库之互联网常用分库分表方案: sql/data_split.md
        - Mybatis使用心德: sql/mybatis.md
    - Linux: 
        - 常用命令: linux/often.md
        - 实用的Linux 命令: linux/ope.md
        - Centos配置 docker java mysql mongodb redis 环境: linux/centos_docker.md
    - Docker: 
        - Docker全科: docker/docker.md    
    - Tool: 
        - Git: tool/git.md
        - Git问题处理: tool/gitquestion.md
        - GitFlow: tool/gitflow.md
        - GitBook: tool/gitbook.md
        - Git提交日志规范: tool/gitcmr.md
        - Markdown: tool/markdown.md
        - CI/CD: tool/cicd.md
        - mkdocs简单使用: tool/mkdocs.md
        - Git的黑魔法: tool/gitstudy.md
  - 微服务:  
        - 基于SpringCloud的微服务架构演变史: micro/spring-cloud.md
        - 分布式锁: micro/fbs-lock.md
        - 微服务设计: micro/design.md
        - 分布式系统与消息的投递: micro/distrimsg.md
        - 基于DDD的微服务设计和开发实战: micro/ddd.md
  - 经验分析:
    - DevOps: exp/devops.md   
    - Micro-Service: exp/micro-service.md
    - Raft算法和Gossip协议: exp/raft-gossip.md
    - 集群和负载均衡: exp/cl.md
    - 人工智能: exp/ai.md
    - 代码原则: exp/code-principle.md
    - 如何成为技术大牛: exp/techbig.md
    - 程序员如何技术成长: exp/learnweetout.md    
    - 产品与技术: exp/pt.md
    - 深度学习框架: exp/four_deep_learning.md
    - 在阿里做了5年技术Leader，我总结出这些套路！: exp/tl.md
    - CTO 技能图谱 : exp/cto.md
  - 医学:
    - 脑炎: doctor/ae.md
  - 构架:
    - 构架拆分: framework/split.md 
    - 分布式、高并发、多线程: framework/fgb.md 
    - 如何理解敏捷开发: framework/agility.md 
    - 走向架构师必备的技能: framework/fwork.md
  - 情感:
    - 情商: emotion/eq.md
    - 工作心得: emotion/workheard.md
    - 看书: emotion/lookbook.md  
    - 4种男朋友: emotion/fmf.md
    - 不上心: emotion/notheart.md
    - 自律: emotion/selfdiscipline.md
    - 喜欢与不喜欢: emotion/notlike.md
    - 晚婚: emotion/latemarry.md
    - 追女生要明白这些事: emotion/understand.md
    - 备胎: emotion/backup.md
    - 为什么追不到她: emotion/chase.md
    - 为什么活着失败: emotion/livefail.md
    - 情绪管理: emotion/emotion.md
    - 废掉的三个迹象: emotion/abolish.md
    - 余生，好好珍惜: emotion/uptime.md
    - 所有的失去，都会以另一种方式归来: emotion/losecome.md
    - 人生有这三种好心态: emotion/threeheart.md
    - 一个感情真相: emotion/onelike.md
    - 情商与道理: emotion/notruth.md
    - 六种男人远离: emotion/smf.md
    - 决定接下来人生归属的，不是努力，而是选择: emotion/select.md
    - 被你拉黑的那个人，你一定很喜欢吧: emotion/nolike.md
    - 余生，学会一个人走，不管有没有人陪: emotion/onepath.md
    - 往后余生还很精彩，别被熬夜拖垮了: emotion/twopath.md
    - 心态好的人，一辈子都好: emotion/lifetime.md
    - 将心比心，方得人心: emotion/hearttoheart.md
    - 别睡太晚，别爱太满，别要太多: emotion/ttt.md
    - 表白: emotion/profess.md
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
