site_name: BurningMyself
site_description: .net,java,php,python,docker,web
site_author: 朽木自雕
site_url: https://burningmyself.github.io/blog/

repo_name: 'burningmyself/blog'
repo_url: 'https://github.com/burningmyself/blog'

theme:
  name: material
nav: 
  - 介绍: index.md 
  - 技术博文: 
    - .NET: 
        - C# 6: net/c_sharp.md
    - Java: 
        - Java特性: java/feature.md 
        - Java类加载: java/load-class.md
        - Orm的优缺点: java/orm.md
    - Python: 
        - Python特性: python/feature.md 
        - Python字符拼接: python/str_joint.md
        - Python语法技巧: python/syntax_rule.md
    - PHP: 
        - 框架: php/kj.md    
    - Web:
        - es6语法: web/es6.md
        - 阿里js样式规范: web/ali_js_style.md
        - node.js文档: web/node.js.md
    - SQL:
        - MySQL优化: sql/mysql_yh.md
        - MySQL日志: sql/mysql_log.md
        - MySQL索引: sql/mysql_index.md
        - MySQL PXC集群: sql/mysql_pxc.md
    - Linux: 
        - 常用命令: linux/often.md
    - Docker: 
        - Docker全科: docker/docker.md    
    - Tool: 
        - Git: tool/git.md
        - Git问题处理: tool/gitquestion.md
        - GitBook: tool/gitbook.md
        - Markdown: tool/markdown.md
  - 微服务:  
        - 基于SpringCloud的微服务架构演变史: micro/spring-cloud.md
        - 分布式锁: micro/fbs-lock.md
        - 微服务设计: micro/design.md
  - 经验分析:
    - DevOps: exp/devops.md   
    - Micro-Service: exp/micro-service.md
    - Raft算法和Gossip协议: exp/raft-gossip.md
    - 集群和负载均衡: exp/cl.md
    - 人工智能: exp/ai.md
    - 情商: exp/eq.md
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde